<?php include 'includes/header.php'; ?>
<?php include 'includes/modals/modals.php'; ?>  

<!-- Contenido de la página principal -->
<h1>Estudiantes</h1>
<div class="content">
<button class="btn btn-success" type="button" onclick="openModal()">Nuevo Estudiante</button>
<table id="example" class="table table-striped table-bordered" style="width:100%">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>edad</th>
                <th>Dirección</th>
                <th>Cedula</th>
                <th>Telefono</th>
                <th>Correo</th>
            </tr>
        </thead>
        <tbody>
        <tr>
                <td>Nixon</td>
                <td>10</td>
                <td>Maracaibo</td>
                <td>V-123456</td>
                <td>123456</td>
                <td>N@gmail.com</td>
            </tr>
            <tr>
                <td>Nixon</td>
                <td>10</td>
                <td>Maracaibo</td>
                <td>V-123456</td>
                <td>123456</td>
                <td>N@gmail.com</td>
            </tr>
            <tr>
                <td>Nixon</td>
                <td>10</td>
                <td>Maracaibo</td>
                <td>V-123456</td>
                <td>123456</td>
                <td>N@gmail.com</td>
            </tr>
            <tr>
                <td>Nixon</td>
                <td>10</td>
                <td>Maracaibo</td>
                <td>V-123456</td>
                <td>123456</td>
                <td>N@gmail.com</td>
            </tr>
            <tr>
                <td>Nixon</td>
                <td>10</td>
                <td>Maracaibo</td>
                <td>V-123456</td>
                <td>123456</td>
                <td>N@gmail.com</td>
            </tr>
            <tr>
                <td>Nixon</td>
                <td>10</td>
                <td>Maracaibo</td>
                <td>V-123456</td>
                <td>123456</td>
                <td>N@gmail.com</td>
            </tr>
            <tr>
                <td>Nixon</td>
                <td>10</td>
                <td>Maracaibo</td>
                <td>V-123456</td>
                <td>123456</td>
                <td>N@gmail.com</td>
            </tr>
            <tr>
                <td>Nixon</td>
                <td>10</td>
                <td>Maracaibo</td>
                <td>V-123456</td>
                <td>123456</td>
                <td>N@gmail.com</td>
            </tr>
            <tr>
                <td>Nixon</td>
                <td>10</td>
                <td>Maracaibo</td>
                <td>V-123456</td>
                <td>123456</td>
                <td>N@gmail.com</td>
            </tr>
            <tr>
                <td>Nixon</td>
                <td>10</td>
                <td>Maracaibo</td>
                <td>V-123456</td>
                <td>123456</td>
                <td>N@gmail.com</td>
            </tr>
            <tr>
                <td>Nixon</td>
                <td>10</td>
                <td>Maracaibo</td>
                <td>V-123456</td>
                <td>123456</td>
                <td>N@gmail.com</td>
            </tr>
            <tr>
                <td>Nixon</td>
                <td>10</td>
                <td>Maracaibo</td>
                <td>V-123456</td>
                <td>123456</td>
                <td>N@gmail.com</td>
            </tr>
            <tr>
                <td>Nixon</td>
                <td>10</td>
                <td>Maracaibo</td>
                <td>V-123456</td>
                <td>123456</td>
                <td>N@gmail.com</td>
            </tr>
            <tr>
                <td>Nixon</td>
                <td>10</td>
                <td>Maracaibo</td>
                <td>V-123456</td>
                <td>123456</td>
                <td>N@gmail.com</td>
            </tr>
            
        </tbody>
        <tfoot>
            <tr>
                <th>Nombre</th>
                <th>Edad</th>
                <th>Dirección</th>
                <th>Cedula</th>
                <th>Telefono</th>
                <th>Correo</th>
            </tr>
        </tfoot>
    </table>
</div>

<?php include 'includes/footer.php'; ?>
